### ISSUE TITLE
How to use it?

### ISSUE THREAD

**Issue by Lip0** [uts-magic-lab/slam_glass#3]
I have my own laser lidar(Sick_Tim561) and robot turtlebot2，I want use this code on my device. In my opinion, it would be set ros topic. The laser lidar topic /scan as input of your slam_glass, but I can not find any tips about this. I am very confuse.
Hope you can teach me to use this programe on my equipment, thank you very much.

**Comment by Lip0** [comment]
Is there anyone can help me?
I can not run your programe. I run slam_glass according to gmapping, but I can not get any map info!!!!!!
Is this programe correct?

**Comment by kunle12** [comment]
Assuming your device is sending correct data to topic `/scan` (both range and intensity), you need to modify launch file  `slam_glass_pr2.launch` and remove remap scan (line 6). Go through the experimental procedure described in the paper and modify the **glassTrigIntensity** parameter in the launch file accordingly. Also set **use_sim_time** to false.

**Comment by Lip0** [comment]
Soory, it can not change anything after altering the launch file slam_glass_pr2.launch according you replay.
The topic /map data is empty,. When I view this topic in the rviz, it remind me that no map received.

**Comment by kunle12** [comment]
Can you show me the outputs when you run the program?

**Comment by Lip0** [comment]
![选区_003](https://user-images.githubusercontent.com/27806288/58523650-e9be9f80-81f7-11e9-9a52-6c64ebbbe95f.png)

**Comment by kunle12** [comment]
It seems that `slam_glass` has not received any input scan data. Otherwise, it should print out many log messages. Check your laser scan output with rostopic and make sure it matches with the expected from `slam_glass`

**Comment by Lip0** [comment]
yeah, When gmapping is running, it will print many messages after certain time. But my laser topic /scan have data. I put a picture about this topic, you cheick it. Add I use this laser topic can running slam_gmapping coorectly.

![选区_005](https://user-images.githubusercontent.com/27806288/58524088-a06f4f80-81f9-11e9-99f7-21f9bc4d0afe.png)

**Comment by Lip0** [comment]
![选区_004](https://user-images.githubusercontent.com/27806288/58524094-acf3a800-81f9-11e9-8add-bd27d323f14b.png)

**Comment by Lip0** [comment]
I have changed launch file as blow.
<launch>
  <param name="use_sim_time" value="false"/>

    <node pkg="slam_glass" type="slam_glass" name="slam_glass" output="screen"> 
      <param name="odom_frame" value="odom_combined"/>
      <param name="map_udpate_interval" value="5.0"/>
      <param name="maxUrange" value="16.0"/>
      <param name="sigma" value="0.05"/>
      <param name="kernelSize" value="1"/>
      <param name="lstep" value="0.05"/>
      <param name="astep" value="0.05"/>
      <param name="iterations" value="5"/>
      <param name="lsigma" value="0.075"/>
      <param name="ogain" value="3.0"/>
      <param name="lskip" value="0"/>
      <param name="srr" value="0.1"/>
      <param name="srt" value="0.2"/>
      <param name="str" value="0.1"/>
      <param name="stt" value="0.2"/>
      <param name="linearUpdate" value="1.0"/>
      <param name="angularUpdate" value="0.5"/>
      <param name="temporalUpdate" value="3.0"/>
      <param name="resampleThreshold" value="0.5"/>
      <param name="particles" value="30"/>
      <param name="xmin" value="-50.0"/>
      <param name="ymin" value="-50.0"/>
      <param name="xmax" value="50.0"/>
      <param name="ymax" value="50.0"/>
      <param name="delta" value="0.05"/>
      <param name="llsamplerange" value="0.01"/>
      <param name="llsamplestep" value="0.01"/>
      <param name="lasamplerange" value="0.005"/>
      <param name="lasamplestep" value="0.005"/>
      <param name="glassTrigIntensity" value="8000.0"/>
      <param name="glassIntensityDelta" value="4000.0"/>
    </node>
</launch>

**Comment by Lip0** [comment]
<launch>
  <param name="use_sim_time" value="false"/>

    <node pkg="slam_glass" type="slam_glass" name="slam_glass" output="screen"> 
      <param name="odom_frame" value="odom_combined"/>
      <param name="map_udpate_interval" value="5.0"/>
      <param name="maxUrange" value="16.0"/>
      <param name="sigma" value="0.05"/>
      <param name="kernelSize" value="1"/>
      <param name="lstep" value="0.05"/>
      <param name="astep" value="0.05"/>
      <param name="iterations" value="5"/>
      <param name="lsigma" value="0.075"/>
      <param name="ogain" value="3.0"/>
      <param name="lskip" value="0"/>
      <param name="srr" value="0.1"/>
      <param name="srt" value="0.2"/>
      <param name="str" value="0.1"/>
      <param name="stt" value="0.2"/>
      <param name="linearUpdate" value="1.0"/>
      <param name="angularUpdate" value="0.5"/>
      <param name="temporalUpdate" value="3.0"/>
      <param name="resampleThreshold" value="0.5"/>
      <param name="particles" value="30"/>
      <param name="xmin" value="-50.0"/>
      <param name="ymin" value="-50.0"/>
      <param name="xmax" value="50.0"/>
      <param name="ymax" value="50.0"/>
      <param name="delta" value="0.05"/>
      <param name="llsamplerange" value="0.01"/>
      <param name="llsamplestep" value="0.01"/>
      <param name="lasamplerange" value="0.005"/>
      <param name="lasamplestep" value="0.005"/>
      <param name="glassTrigIntensity" value="8000.0"/>
      <param name="glassIntensityDelta" value="4000.0"/>
    </node>
</launch>

**Comment by Lip0** [comment]
![选区_007](https://user-images.githubusercontent.com/27806288/58524219-1bd10100-81fa-11e9-8841-d90e8ac7726c.png)

**Comment by kunle12** [comment]
please use text instead of images if you can. Do you have odometry inputs to `slam_glass`?

**Comment by Lip0** [comment]
The reason seems is the tf error. 
I want to know the result of this programe is really good? I can get a map of  environment  with transparent glass?
Can you describe this?

**Comment by kunle12** [comment]
We had good results under the environments we tested (see our paper). I cannot say for sure that it will work well in your environment with your sensor. You will have to evaluate the software yourself.

**Comment by Lip0** [comment]
OK then，my robot have odometry topic. How to set odometry inputs to slam_glass?

**Comment by kunle12** [comment]
change **odom_frame** parameter.
