### ISSUE TITLE
registerScanG problem

### ISSUE THREAD

**Issue by liyaozone** [uts-magic-lab/slam_glass#5]
Hello,
     I am reading your slam_glass codes.And in scanmatcher.cpp, I cannot understand the registerScanG code.
```
      if (hasSigAt &&  prang <= peakRange && fabs(*hasSigAt - distance) < distAllowance) 
      {
        // get mid/peak of the detected glass laser data curve
        double * peak = hasSigAt + (prang >> 1);
        double * peakAng = ((int)(peak - (readings + m_initialBeamsSkip))) + m_laserAngles + m_initialBeamsSkip;

        //glassmap.push_back( { pose, *hasSigAt,
          //*(((int)(hasSigAt - (readings + m_initialBeamsSkip))) + m_laserAngles + m_initialBeamsSkip), timestamp } );
        glassmap.push_back( { pose, *peak, *peakAng, timestamp } );
        //glassmap.push_back( { pose, *r,
          //*(((int)(r - (readings + m_initialBeamsSkip))) + m_laserAngles + m_initialBeamsSkip), timestamp } );
        detectedPoints++;
        hasSigAt = NULL;
      }
```

```
 // get mid/peak of the detected glass laser data curve
double * peak = hasSigAt + (prang >> 1);
double * peakAng = ((int)(peak - (readings + m_initialBeamsSkip))) + m_laserAngles + m_initialBeamsSkip;
```
what is this meaning?

**Comment by kunle12** [comment]
This piece of code going through the (double) array of range readings and intensity readings and use a very simple two adjacent (intensity) points to calculate gradient changes. If the gradient change is greater than `detectionGrad` for both up and down under the constraints of `triggerIntensity`, `peakRange` etc, then we believe we found a (assumed) _symmetrical_ "hump" that represents the returning laser intensity profile from glass. `hasSigAt` is the bottom of the peak, `prang` is the size, peak is the mid point of the profile and peakAng is the corresponding angle. Sorry for the silly naming.

**Comment by liyaozone** [comment]
OK! Great! I know. Thanks a lot. I have a question about the glass_match function, and I will upload later.
